get_forms:
  from_year: 2021
  to_year:   2022
  quaters: ## ["QTR1", "QTR2", "QTR3", "QTR4"]
    - "QTR1"
    - "QTR2"
    - "QTR3"
    - "QTR4"
data_path: "/opt/airflow/data/"
forms_parser:
  is_existed_only_mapping: "False"
  file_name: "forms.csv"
  mapping:   "mapping.csv"